### ISSUE TITLE
There is a typo in package.json

### ISSUE THREAD

**Issue by lgmcode** [atomclip/windows-arm-none-eabi#2]
Very nice extension for VSC and STM32.
There is a typo in package.json.
The repository.url should be "https://github.com/atomclip/windows-arm-none-eabi.git"
(the "none" has lost a "e")

**Comment by xiaolongba** [comment]
@lgmcode yes,i am also found this issue,but the ver0.10 can support "make.exe",so how can i use it?can u give me some suggestions？thanks

**Comment by atomclip** [comment]
@lgmcode 

Thanks I will fix this.

**Comment by lgmcode** [comment]
@atomclip Cool
